### ISSUE TITLE
Sorry, failed to upload file.

### ISSUE THREAD

**Issue by Luffy03** [Junjue-Wang/LoveDA#22]
Sth wrong with the website?

**Comment by Junjue-Wang** [comment]
Yes. The new website will be fixed this Monday I think

**Comment by Luffy03** [comment]
> Yes. The new website will be fixed this Monday I think
ok, thx. Look forward to it.

**Comment by Junjue-Wang** [comment]
The website was already fixed right now.

**Comment by Luffy03** [comment]
> The website was already fixed right now.

thank you very much!

**Comment by lyhnsn** [comment]
> The website was already fixed right now.

Sorry, but I still can't upload the zip file on the web, is there any problem yet?

**Comment by lyhnsn** [comment]
> The website was already fixed right now.

Sorry, but I still can't upload the zip file on the web, is there still any problem?

**Comment by Luffy03** [comment]
> > The website was already fixed right now.
> 
> Sorry, but I still can't upload the zip file on the web, is there still any

**Comment by Luffy03** [comment]
This problem always happens.......

**Comment by Junjue-Wang** [comment]
You can report this error at this [issue](https://github.com/codalab/codalab-competitions/issues/3053). Or maybe you can alternatively use the old server, which is always online. https://competitions.codalab.org/competitions/35865#results

**Comment by lyhnsn** [comment]
> 
thx, but maybe i uploaded the wrong format

> You can report this error at this [issue](https://github.com/codalab/codalab-competitions/issues/3053). Or maybe you can alternatively use the old server, which is always online. https://competitions.codalab.org/competitions/35865#results



> You can report this error at this [issue](https://github.com/codalab/codalab-competitions/issues/3053). Or maybe you can alternatively use the old server, which is always online. https://competitions.codalab.org/competitions/35865#results

thx and i found my format was wrong.

**Comment by Luffy03** [comment]
> You can report this error at this [issue](https://github.com/codalab/codalab-competitions/issues/3053). Or maybe you can alternatively use the old server, which is always online. https://competitions.codalab.org/competitions/35865#results
I can not upload the file on this server today.
https://codalab.lisn.upsaclay.fr/competitions/424#participate-submit_results

**Comment by Luffy03** [comment]
![image](https://user-images.githubusercontent.com/52514670/146508644-ff3fec47-b055-4050-8fa5-540538e72c3f.png)
ok, here is the reason

**Comment by Didayolo** [comment]
Is there still a problem here?
If yes, can you provide more information about it?
